import productImage from "./ProductImages";
const ProductData = [
  {
    id: 1,
    imageSrc: productImage.sailorShort,
    productName: "Sailor Short",
    price: "145.02",
    productCategory: "women product",
  },
  {
    id: 2,
    imageSrc: productImage.tieWhite,
    productName: "Tie White",
    price: "145.02",
    productCategory: "women product",
  },
  {
    id: 3,
    imageSrc: productImage.whiteColor,
    productName: "White Color",
    price: "145.02",
    productCategory: "women product",
  },
  {
    id: 4,
    imageSrc: productImage.leatherTop,
    productName: "Leather Top",
    price: "145.02",
    productCategory: "women product",
  },
  {
    id: 5,
    imageSrc: productImage.kidSwag,
    productName: "Kid Swag",
    price: "145.02",
    productCategory: "kid product",
  },
  {
    id: 6,
    imageSrc: productImage.kidSare,
    productName: "Kid Sare",
    price: "145.02",
    productCategory: "kid product",
  },
  {
    id: 7,
    imageSrc: productImage.kidFormal,
    productName: "Kid Formal",
    price: "145.02",
    productCategory: "kid product",
  },
  {
    id: 8,
    imageSrc: productImage.kidJeans,
    productName: "Kid Jeans",
    price: "145.02",
    productCategory: "kid product",
  },
  {
    id: 9,
    imageSrc: productImage.menFormal,
    productName: "Men Formal",
    price: "145.02",
    productCategory: "men product",
  },
  {
    id: 10,
    imageSrc: productImage.menJacket,
    productName: "Men Jacket",
    price: "145.02",
    productCategory: "men product",
  },
  {
    id: 11,
    imageSrc: productImage.menSuit,
    productName: "Men Suit",
    price: "145.02",
    productCategory: "men product",
  },
  {
    id: 12,
    imageSrc: productImage.menStylish,
    productName: "Men Stylish",
    price: "145.02",
    productCategory: "men product",
  },
  {
    id: 13,
    imageSrc: productImage.unisex1,
    productName: "Unisex 1",
    price: "145.02",
    productCategory: "unisex product",
  },
  {
    id: 14,
    imageSrc: productImage.unisex2,
    productName: "Unisex 2",
    price: "145.02",
    productCategory: "unisex product",
  },
  {
    id: 15,
    imageSrc: productImage.unisex3,
    productName: "Unisex 3",
    price: "145.02",
    productCategory: "unisex product",
  },
  {
    id: 16,
    imageSrc: productImage.unisex4,
    productName: "Unisex 4",
    price: "145.02",
    productCategory: "unisex product",
  },
  {
    id: 17,
    imageSrc: productImage.sneakerImg1,
    productName: "Sneaker 1",
    price: "145.02",
    productCategory: "sneaker product",
  },
  {
    id: 18,
    imageSrc: productImage.sneakerImg2,
    productName: "Sneaker 2",
    price: "145.02",
    productCategory: "sneaker product",
  },
  {
    id: 19,
    imageSrc: productImage.sneakerImg3,
    productName: "Sneaker 3",
    price: "145.02",
    productCategory: "sneaker product",
  },
  {
    id: 20,
    imageSrc: productImage.sneakerImg4,
    productName: "Sneaker 4",
    price: "145.02",
    productCategory: "sneaker product",
  },
  {
    id: 21,
    imageSrc: productImage.summer1,
    productName: "Summer 1",
    price: "145.02",
    productCategory: "summer product",
  },
  {
    id: 22,
    imageSrc: productImage.summer2,
    productName: "Summer 2",
    price: "145.02",
    productCategory: "summer product",
  },
  {
    id: 23,
    imageSrc: productImage.summer3,
    productName: "Summer 3",
    price: "145.02",
    productCategory: "summer product",
  },
  {
    id: 24,
    imageSrc: productImage.summer4,
    productName: "Summer 4",
    price: "145.02",
    productCategory: "summer product",
  },
];

export default ProductData;
